### ISSUE TITLE
Use `failure` instead of `std::error::Error`

### ISSUE THREAD

**Issue by ipetkov** [ipetkov/conch-runtime#12]
* Migrate all errors in this crate to using `failure`: instead of implementing `std::error::Error` we should just implement `failure::Fail` instead

https://crates.io/crates/failure
https://crates.io/crates/failure_derive

**Comment by linkmauve** [comment]
failure is now [deprecated](https://github.com/rust-lang-nursery/failure#failure---a-new-error-management-story), I’d recommend to close this issue and continue using the perfectly fine `std::error::Error` instead.

**Comment by ipetkov** [comment]
Yep, this was done in 5deb6af53b1e08e07345946a177311b64c475c22

**Comment by linkmauve** [comment]
Thanks!
